# Generated by Django 3.0.8 on 2020-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='balance_due',
            field=models.CharField(default='0.00', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.CharField(default='August 9, 2020', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
