# Generated by Django 3.0.8 on 2020-07-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_book', '0002_auto_20200714_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
    ]
